[package]
name = "tinyspline-rs"
version = "0.1.0"
edition = "2021"

[dependencies]

[profile.dev]
debug = 1
opt-level = 3
lto = true
codegen-units = 1

[profile.release]
opt-level = 3
lto = true
codegen-units = 1